### Post Create Patients
POST http://localhost:4000/patients/add
Content-Type: application/json

{
      "name": "Zankhana Parekh with Billing Account",
      "email": "zankhana@gmail.com",
      "address": "895 Main St, Springfield, IL",
      "dateOfBirth": "1975-08-14",
      "registeredDate": "2026-01-24"
}

###