### Post Create Patients
POST http://localhost:4000/patients/add
Content-Type: application/json

{
      "name": "ioerp",
      "email": "iorep@gmail.com",
      "address": "ioerp, Cumming",
      "dateOfBirth": "1966-11-25",
      "registeredDate": "1996-08-24"
}

###