### Post Create Patients
POST http://localhost:4000/patients/add
Content-Type: application/json

{
      "name": "cool Bubby with Billing Account",
      "email": "bubby@gmail.com",
      "address": "62, East ave, Cumming",
      "dateOfBirth": "1975-08-21",
      "registeredDate": "2026-01-24"
}

###