### GET request to get all patients
GET http://localhost:4000/patients

### API GATEWAY
GET http://localhost:4004/api/patients


### API GATEWAY WITH TOKEN
GET http://localhost:4004/api/patients
Authorization: Bearer {{token}}